#!/usr/bin/sh
code --install-extension 42crunch.vscode-openapi
code --install-extension 4ops.terraform
code --install-extension adpyke.vscode-sql-formatter
code --install-extension batisteo.vscode-django
code --install-extension charliermarsh.ruff
code --install-extension codezombiech.gitignore
code --install-extension donjayamanne.python-environment-manager
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension golang.go
code --install-extension gruntfuggly.todo-tree
code --install-extension hbenl.vscode-test-explorer
code --install-extension ibm.output-colorizer
code --install-extension jacobpfeifer.pfeifer-hurl
code --install-extension jdinhlife.gruvbox
code --install-extension jebbs.plantuml
code --install-extension jock.svg
code --install-extension jonathanharty.gruvbox-material-icon-theme
code --install-extension ketho.wow-api
code --install-extension kevinrose.vsc-python-indent
code --install-extension littlefoxteam.vscode-python-test-adapter
code --install-extension mechatroner.rainbow-csv
code --install-extension mgmcdermott.vscode-language-babel
code --install-extension mikestead.dotenv
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.black-formatter
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.test-adapter-converter
code --install-extension pkief.material-icon-theme
code --install-extension polymeilex.wgsl
code --install-extension rangav.vscode-thunder-client
code --install-extension rebornix.toggle
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust-analyzer
code --install-extension s-nlf-fh.glassit
code --install-extension sainnhe.gruvbox-material
code --install-extension sumneko.lua
code --install-extension tamasfe.even-better-toml
code --install-extension timonwong.shellcheck
code --install-extension tomphilbin.gruvbox-themes
code --install-extension usernamehw.errorlens
code --install-extension vadimcn.vscode-lldb
code --install-extension vscode-icons-team.vscode-icons
code --install-extension waderyan.gitblame
code --install-extension zxh404.vscode-proto3
