[tools]
"cargo:bat" = "0.26"
"cargo:eza" = "0.23"
"cargo:git-delta" = "0.19"
"cargo:hurl" = "7.0.0"
"cargo:hyperfine" = "1.19.0"
"cargo:just" = "1.43.0"
"cargo:neovide" = "0.16"
"cargo:ripgrep" = "15.1"
"cargo:zoxide" = "0.9"
"github:sst/opencode" = "1.2.27"
gradle = "latest"
java = "openjdk-21"
lazygit = "0.61"
node = "latest"
rust = "1.94"
zig = "0.15.2"
zola = "0.19.2"
