[tools]
bat = "0.26"
"cargo:neovide" = "0.16"
delta = "0.19.2"
eza = "0.23"
"github:sst/opencode" = "1.2.27"
helm = "4.2.3"
hurl = "8.0.1"
hyperfine = "1.20.0"
just = "1.43.1"
kubecolor = "0.6.0"
kubectl = "1.36.3"
kubeseal = "0.38.4"
lazygit = "0.61"
node = "26.5.1"
pi = "0.84.2"
ripgrep = "15.1.0"
rust = "1.96"
tree-sitter = "0.26.12"
zellij = "0.44.3"
zig = "0.15.2"
zola = "0.22.1"
zoxide = "0.10.0"

[settings]
pin = true
